services:
  - type: web
    name: botzmine-whatsapp-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true

    envVars:
      - key: FIREBASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production

    disk:
      name: sessions-storage
      mountPath: /opt/render/project/src
      sizeGB: 1
